Boar 55
proostack/boardmate pull request #26
Opened 2022-09-01 18:28 UTC by Eugene44-hub

2022-09-02 08:17 UTC, jbrainz requested changes

2022-09-02 08:17 UTC, jbrainz commented on src/navigation/index.tsx
> +            <ApolloProvider client={client()}>
why client() ?

2022-09-02 08:17 UTC, jbrainz commented on src/screens/ProfileMenu/ProfileMenu.tsx
> +          <TouchableOpacity key={index} onPress={()=>{item.text!=="Log out"?navigation.navigate(item.navigate):dispatch(setToken(null))}}>
What is going on here?
what are you trying to achieve?

2022-09-02 08:25 UTC, Eugene44-hub commented on src/screens/ProfileMenu/ProfileMenu.tsx
> +          <TouchableOpacity key={index} onPress={()=>{item.text!=="Log out"?navigation.navigate(item.navigate):dispatch(setToken(null))}}>
> What is going on here? what are you trying to achieve?

was making the logout . On default the token is null. When the user is logged in there is a token, then when the user is logged out the token is set to null

2022-09-02 08:27 UTC, Eugene44-hub commented on src/navigation/index.tsx
> +            <ApolloProvider client={client()}>
I turned the client into a function because i was unable to use the useDispatch hook

2022-09-02 08:29 UTC, jbrainz commented on src/navigation/index.tsx
> +            <ApolloProvider client={client()}>
is this recommended or it's a hack?

2022-09-02 08:30 UTC, jbrainz commented on src/screens/ProfileMenu/ProfileMenu.tsx
> +          <TouchableOpacity key={index} onPress={()=>{item.text!=="Log out"?navigation.navigate(item.navigate):dispatch(setToken(null))}}>
extract the logic to a function so it can be more readable.

2022-09-02 08:36 UTC, Eugene44-hub commented on src/navigation/index.tsx
> +            <ApolloProvider client={client()}>
> is this recommended or it's a hack?

It's a hack.

2022-09-02 08:43 UTC, Eugene44-hub commented on src/navigation/index.tsx
> +            <ApolloProvider client={client()}>
![image](https://user-images.githubusercontent.com/75457464/188100710-d124f5f6-332f-470e-bba1-d6bee39126e8.png)

2022-09-03 07:48 UTC, jbrainz approved these changes

2022-09-04 00:26 UTC, merged