Update user profile
proostack/boardmate pull request #28
Opened 2022-09-05 23:31 UTC by Eugene44-hub

The design hasn't be completed but the request works fine. When the design is updated this branch will be updated

2022-09-09 01:19 UTC, Eugene44-hub commented
> The design hasn't be completed but the request works fine. When the design is updated this branch will be updated

2022-09-10 11:43 UTC, jbrainz requested changes

2022-09-10 11:43 UTC, jbrainz commented on src/components/countryPicker/SelectCountry.tsx
> +    setCountryDet(country)
what is setCountryDet?

2022-09-10 11:43 UTC, jbrainz commented on src/components/countryPicker/SelectCountry.tsx
>      setCallingCode(country.callingCode)
what is setCallingCode?

2022-09-10 11:43 UTC, jbrainz commented on src/components/countryPicker/SelectCountry.tsx
> +              <TouchableOpacity onPress={() =>onOpen && onOpen()} style={{width:"100%"}}>
i don't understand why you are checking for onOpen?

2022-09-10 11:43 UTC, jbrainz commented on src/screens/ProfileMenu/Profile.tsx
> +  const [show, setShow] = useState<boolean>(true)
please create a custom hook to manage this component.
and move all this local state hook to a central hook file. you component should be as neat as possible

2022-09-10 11:43 UTC, jbrainz commented on src/screens/ProfileMenu/Profile.tsx
> +    if (!loading && called) {
i really don't understand why you are doing it this way.

2022-09-10 11:43 UTC, jbrainz commented on src/screens/ProfileMenu/Profile.tsx
> +              image={defaultUsers[0].image}
what is default users?
why not use an object since you just have one element in the array?

2022-09-10 11:43 UTC, jbrainz commented on src/store/user.ts
> +      phone: [""]
what is this?

2022-09-10 11:43 UTC, jbrainz commented on src/screens/ProfileMenu/Profile.tsx
> +  const profileDetails: string[] = [
do we still need this mock data?

2022-09-10 12:27 UTC, Eugene44-hub commented on src/components/countryPicker/SelectCountry.tsx
> +    setCountryDet(country)
To get the details of a country e.g region, the calling code are all contained in the countryDet

2022-09-10 12:28 UTC, Eugene44-hub commented on src/components/countryPicker/SelectCountry.tsx
>      setCallingCode(country.callingCode)
To get a country's calling code e.g nigeria +234

2022-09-10 12:33 UTC, Eugene44-hub commented on src/screens/ProfileMenu/Profile.tsx
> +  const profileDetails: string[] = [
Yes because those data such as the date, wallet balance are not available on the api yet. I will speak to max about it

2022-09-10 12:38 UTC, Eugene44-hub commented on src/screens/ProfileMenu/Profile.tsx
> +              image={defaultUsers[0].image}
No it doesn't contain on one user. it contains several users. It's a mockup data on the redux store.

2022-09-10 12:40 UTC, Eugene44-hub commented on src/store/user.ts
> +      phone: [""]
The phone number from the react native country pick is structured in am array of one single element of string, here am setting the initial value to an empty string array

2022-09-10 12:45 UTC, Eugene44-hub commented on src/screens/ProfileMenu/Profile.tsx
> +    if (!loading && called) {
I couldn't think of a better way. But what i am doing here is if the updateProfile mutation is fired and it was successful it should return the data updated

2022-09-10 13:07 UTC, Eugene44-hub commented on src/components/countryPicker/SelectCountry.tsx
> +              <TouchableOpacity onPress={() =>onOpen && onOpen()} style={{width:"100%"}}>
it's saying.
 Cannot invoke an object which is possibly 'undefined'.ts(2722) 
from the react-native-country-picker so i use this hack to bypass

2022-09-10 13:55 UTC, jbrainz commented on src/components/countryPicker/SelectCountry.tsx
> +    setCountryDet(country)
please name the variables properly

2022-09-10 14:01 UTC, jbrainz commented on src/screens/ProfileMenu/Profile.tsx
> +              image={defaultUsers[0].image}
do we still need to mock data?

2022-09-10 14:04 UTC, jbrainz commented on src/store/user.ts
> +      phone: [""]
it can just be [] right?

2022-09-10 18:12 UTC, Eugene44-hub commented on src/screens/ProfileMenu/Profile.tsx
> +              image={defaultUsers[0].image}
Yes we need to mock data on some places like wallet details and ratings and images they are not available on the api yet

2022-09-10 18:43 UTC, Eugene44-hub commented on src/store/user.ts
> +      phone: [""]
No it throws error too when i do that

2022-09-12 06:52 UTC, jbrainz requested changes

2022-09-12 06:52 UTC, jbrainz commented on src/hooks/useAuth.ts
> +      if (error) {
move this block up and return early

2022-09-12 06:52 UTC, jbrainz commented on src/hooks/useAuth.ts
> +      else {
so it would be:
```
if(error){
return
}
 if(called && !loading){
callback()
}
```

2022-09-13 07:01 UTC, jbrainz approved these changes

2022-09-13 11:47 UTC, merged